<?php

namespace fat2fast\auth\models;

use yii\behaviors\TimestampBehavior;

/**
 * This is the model class for table "sms_notification".
 *
 * @property int $id_sms_notification
 * @property int $uid
 * @property string $type
 * @property int $to
 * @property string $message
 * @property string $note
 * @property int $status
 * @property int $created_at
 * @property int $updated_at
 */
class SmsNotification extends \yii\db\ActiveRecord
{
    const STATUS_SENDING = 1;
    const STATUS_SUCCESS = 2;
    const STATUS_ERROR = 3;

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'sms_notification';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['uid', 'status', 'created_at', 'updated_at'], 'integer'],
            [['note'], 'string'],
            [['type'], 'string', 'max' => 11],
            [['message', 'to'], 'string', 'max' => 255],
        ];
    }

    public function behaviors()
    {
        return array_merge(parent::behaviors(), [
            TimestampBehavior::class
        ]); // TODO: Change the autogenerated stub
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id_sms_notification' => 'Id Sms Notification',
            'uid' => 'Uid',
            'type' => 'Type',
            'to' => 'To',
            'message' => 'Message',
            'note' => 'Note',
            'status' => 'Status',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }
}
